# Generated by Django 3.2.15 on 2022-12-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_trade_id', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Users data',
            },
        ),
    ]
